[package]
name = "macrooo_derive"
version = "0.1.0"
authors = ["junefar <ljunf817@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro=true

[dependencies]
quote = "1.0.7"
syn = "1.0.46"